export default {
  strings: [],
  speed: 100,
  cursor: true,
  cursorChar: "|",
  cursorSpeed: 1000,
  deleteSpeed: null,
  lifeLike: true,
  breakLines: true,
  startDelay: 250,
  startDelete: false,
  nextStringDelay: 750,
  loop: false,
  loopDelay: null,
  html: true,
  waitUntilVisible: false,
  beforeString: false,
  afterString: false,
  beforeStep: false,
  afterStep: false,
  afterComplete: false
};
